# Generated by Django 5.1.4 on 2026-06-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='chat_room',
        ),
    ]
