# Generated by Django 5.1.4 on 2025-01-31 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistUploadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspended_by_admin', models.BooleanField(default=False)),
                ('upload_limit', models.PositiveIntegerField(default=10)),
                ('uploads_used', models.PositiveIntegerField(default=0)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
