# Generated by Django 5.1.4 on 2025-02-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wants_to_participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='remaining_votes',
            field=models.IntegerField(default=0),
        ),
    ]
