# Generated by Django 5.1.4 on 2025-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_download_content',
            field=models.BooleanField(default=False),
        ),
    ]
