# Generated by Django 5.1.4 on 2025-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_can_download_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_on_artist_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_on_new_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
