# Generated by Django 5.1.4 on 2026-02-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_otp_is_active_otp_last_vote_reset_at_otp_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
    ]
