# Generated by Django 5.1.4 on 2026-06-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_votingtokenpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_free_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_suspended_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
