# Generated by Django 5.1.4 on 2026-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_votingtokenpolicy_voting_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingtokenpolicy',
            name='message_retention_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
