# Generated by Django 5.1.4 on 2026-06-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
        ('livestream', '0002_remove_livestream_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
