# Generated by Django 5.1.4 on 2026-06-15 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count_user_one', models.PositiveIntegerField(default=0)),
                ('unread_count_user_two', models.PositiveIntegerField(default=0)),
                ('last_contact_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_chat_threads_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_chat_threads_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_contact_at'],
                'unique_together': {('user_one', 'user_two')},
            },
        ),
    ]
