# Generated by Django 5.1.4 on 2026-06-20 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_matchrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peerchatthread',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peerchatthread',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peerchatthread',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_peer_chat_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
