# Generated by Django 5.1.4 on 2026-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_peerchatthread_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerchatthread',
            name='unlocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
