# Generated by Django 5.1.4 on 2025-01-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_payment_options_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='admin_suspend_limits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='free_uploads_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='free_votes_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='subscriptions.payment'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
