# Generated by Django 5.1.4 on 2025-01-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_admin_suspend_limits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='admin_suspend_limits',
            new_name='suspended_by_admin',
        ),
        migrations.CreateModel(
            name='ArtistUploadLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploads_used', models.PositiveIntegerField(default=0)),
                ('upload_limit', models.PositiveIntegerField(default=10)),
                ('reset_on_payment', models.BooleanField(default=False)),
                ('suspended_by_admin', models.BooleanField(default=False)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_upload_limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
