# Generated by Django 5.1.4 on 2025-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
