# Generated by Django 5.1.4 on 2025-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_vote_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='stream_key',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
