# Generated by Django 5.1.4 on 2025-01-19 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_liveperformance_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveperformance',
            name='stream_key',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
