# Generated by Django 5.1.4 on 2025-01-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_liveperformance_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveperformance',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
