# Generated by Django 5.1.4 on 2025-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_liveperformance_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='use_camera',
            field=models.BooleanField(default=True),
        ),
    ]
