# Generated by Django 5.1.4 on 2025-01-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_artistsubscription_contentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistuploadlimit',
            name='suspended_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_upload_limit', to=settings.AUTH_USER_MODEL),
        ),
    ]
