# Generated by Django 5.1.4 on 2025-01-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_content_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='fan',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='ContentReport',
        ),
    ]
