# Generated by Django 5.1.4 on 2025-02-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_rename_fan_comment_user_delete_contentreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistSubscription',
        ),
    ]
