# Generated by Django 5.1.4 on 2025-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_delete_artistsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='upload_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
