# Generated by Django 5.1.4 on 2025-02-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_vote_otp_code_vote_tag_badge_participationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
