# Generated by Django 5.1.4 on 2025-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_genre_content_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='base_value',
            field=models.IntegerField(default=0),
        ),
    ]
