# Generated by Django 5.1.4 on 2025-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_vote_base_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='base_value',
            field=models.IntegerField(),
        ),
    ]
