# Generated by Django 5.1.4 on 2025-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_vote_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_approved_for_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_badge_vote',
            field=models.BooleanField(default=False),
        ),
    ]
