# Generated by Django 5.1.4 on 2025-02-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_content_is_approved_for_voting_vote_is_badge_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='multiplier',
        ),
    ]
