# Generated by Django 5.1.4 on 2025-02-13 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_badge_multiplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistuploadlimit',
            name='reset_on_payment',
        ),
        migrations.RemoveField(
            model_name='artistuploadlimit',
            name='suspended_by_admin',
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_limit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='upload_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='uploads_used',
            field=models.IntegerField(default=0),
        ),
    ]
