# Generated by Django 5.1.4 on 2025-02-13 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_artistuploadlimit_reset_on_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistuploadlimit',
            name='reset_on_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistuploadlimit',
            name='suspended_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_upload_limit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='upload_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='artistuploadlimit',
            name='uploads_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
