# Generated by Django 5.1.4 on 2025-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveperformance',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
