# Generated by Django 5.1.4 on 2025-06-27 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_liveperformance_is_restricted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='views',
        ),
        migrations.AddField(
            model_name='content',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
