# Generated by Django 5.1.4 on 2025-06-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_remove_content_views_content_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
