# Generated by Django 5.1.4 on 2026-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_content_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/'),
        ),
    ]
