# Generated by Django 5.1.4 on 2026-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_content_youtube_url_alter_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('video', 'Video'), ('art', 'Art'), ('fashion', 'Fashion'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
